# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Static Site generate workflow

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.20.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Setup environment
      run: npm run setup
    - name: Generator running
      run: yarn run gen-ubuntu
    - name: Generate doc list
      run: yarn run gen-doclist
    - name: Clean up
      run: yarn local-clean
    - name: Pack static site
      run: yarn pack-site
    - name: Capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuxt.tar.gz
        path: nuxt.tar.gz
